name: Deploy ApiCatalogo 

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Build Project
        run: dotnet build ./src/ApiCatalogo.API/ApiCatalogo.API.csproj --no-restore

      